# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

variables:
  rgname:"ssrg"
  location:"westindia"

steps:
- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'AzureConnection'
    ScriptType: 'FilePath'
    ScriptPath: 'script.ps'
    azurePowerShellVersion: 'LatestVersion'
